-- S&P 500 constituents.
--
-- Symbols and company names are the real index constituents, taken from the public
-- datasets/s-and-p-500-companies list. Everything else here is synthetic: this app has no
-- market-data feed, so prices are produced by the GBM simulator and the parameters below only
-- have to make each sector behave recognisably.
--
--   initial_price  deterministic pseudo-price derived from the symbol, so every developer's
--                  database starts identical. NOT a real quote.
--   drift/vol      annualized, assigned per GICS sector.
--   rng_seed       3000-series, keeping these distinct from the 1000-series tradables and the
--                  2000-series indices already seeded in seed_marketdata.sql.
--
-- The index itself (SPX) lives in seed_marketdata.sql and is deliberately not tradable; these
-- 503 constituents are. The count is 503, not 500, because several companies have two share
-- classes in the index.
--
-- market is 'US' rather than the real listing venue: the constituent list carries no
-- exchange column, and inventing one per symbol would be fabricated data.

INSERT INTO trading.instruments
    (symbol, instrument_name, asset_class, market, currency, is_tradable)
VALUES
    ('MMM', '3M', 'EQUITY', 'US', 'USD', TRUE),
    ('AOS', 'A. O. Smith', 'EQUITY', 'US', 'USD', TRUE),
    ('ABT', 'Abbott Laboratories', 'EQUITY', 'US', 'USD', TRUE),
    ('ABBV', 'AbbVie', 'EQUITY', 'US', 'USD', TRUE),
    ('ACN', 'Accenture', 'EQUITY', 'US', 'USD', TRUE),
    ('ADBE', 'Adobe Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('AMD', 'Advanced Micro Devices', 'EQUITY', 'US', 'USD', TRUE),
    ('AES', 'AES Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('AFL', 'Aflac', 'EQUITY', 'US', 'USD', TRUE),
    ('A', 'Agilent Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('APD', 'Air Products', 'EQUITY', 'US', 'USD', TRUE),
    ('ABNB', 'Airbnb', 'EQUITY', 'US', 'USD', TRUE),
    ('AKAM', 'Akamai Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('ALB', 'Albemarle Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('ARE', 'Alexandria Real Estate Equities', 'EQUITY', 'US', 'USD', TRUE),
    ('ALGN', 'Align Technology', 'EQUITY', 'US', 'USD', TRUE),
    ('ALLE', 'Allegion', 'EQUITY', 'US', 'USD', TRUE),
    ('LNT', 'Alliant Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('ALL', 'Allstate', 'EQUITY', 'US', 'USD', TRUE),
    ('GOOGL', 'Alphabet Inc. (Class A)', 'EQUITY', 'US', 'USD', TRUE),
    ('GOOG', 'Alphabet Inc. (Class C)', 'EQUITY', 'US', 'USD', TRUE),
    ('MO', 'Altria', 'EQUITY', 'US', 'USD', TRUE),
    ('AMZN', 'Amazon', 'EQUITY', 'US', 'USD', TRUE),
    ('AMCR', 'Amcor', 'EQUITY', 'US', 'USD', TRUE),
    ('AEE', 'Ameren', 'EQUITY', 'US', 'USD', TRUE),
    ('AEP', 'American Electric Power', 'EQUITY', 'US', 'USD', TRUE),
    ('AXP', 'American Express', 'EQUITY', 'US', 'USD', TRUE),
    ('AIG', 'American International Group', 'EQUITY', 'US', 'USD', TRUE),
    ('AMT', 'American Tower', 'EQUITY', 'US', 'USD', TRUE),
    ('AWK', 'American Water Works', 'EQUITY', 'US', 'USD', TRUE),
    ('AMP', 'Ameriprise Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('AME', 'Ametek', 'EQUITY', 'US', 'USD', TRUE),
    ('AMGN', 'Amgen', 'EQUITY', 'US', 'USD', TRUE),
    ('APH', 'Amphenol', 'EQUITY', 'US', 'USD', TRUE),
    ('ADI', 'Analog Devices', 'EQUITY', 'US', 'USD', TRUE),
    ('AON', 'Aon plc', 'EQUITY', 'US', 'USD', TRUE),
    ('APA', 'APA Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('APO', 'Apollo Global Management', 'EQUITY', 'US', 'USD', TRUE),
    ('AAPL', 'Apple Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('AMAT', 'Applied Materials', 'EQUITY', 'US', 'USD', TRUE),
    ('APP', 'AppLovin', 'EQUITY', 'US', 'USD', TRUE),
    ('APTV', 'Aptiv', 'EQUITY', 'US', 'USD', TRUE),
    ('ACGL', 'Arch Capital Group', 'EQUITY', 'US', 'USD', TRUE),
    ('ADM', 'Archer Daniels Midland', 'EQUITY', 'US', 'USD', TRUE),
    ('ARES', 'Ares Management', 'EQUITY', 'US', 'USD', TRUE),
    ('ANET', 'Arista Networks', 'EQUITY', 'US', 'USD', TRUE),
    ('AJG', 'Arthur J. Gallagher & Co.', 'EQUITY', 'US', 'USD', TRUE),
    ('AIZ', 'Assurant', 'EQUITY', 'US', 'USD', TRUE),
    ('T', 'AT&T', 'EQUITY', 'US', 'USD', TRUE),
    ('ATO', 'Atmos Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('ADSK', 'Autodesk', 'EQUITY', 'US', 'USD', TRUE),
    ('ADP', 'Automatic Data Processing', 'EQUITY', 'US', 'USD', TRUE),
    ('AZO', 'AutoZone', 'EQUITY', 'US', 'USD', TRUE),
    ('AVY', 'Avery Dennison', 'EQUITY', 'US', 'USD', TRUE),
    ('AXON', 'Axon Enterprise', 'EQUITY', 'US', 'USD', TRUE),
    ('BKR', 'Baker Hughes', 'EQUITY', 'US', 'USD', TRUE),
    ('BALL', 'Ball Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('BAC', 'Bank of America', 'EQUITY', 'US', 'USD', TRUE),
    ('BAX', 'Baxter International', 'EQUITY', 'US', 'USD', TRUE),
    ('BDX', 'Becton Dickinson', 'EQUITY', 'US', 'USD', TRUE),
    ('BRK.B', 'Berkshire Hathaway', 'EQUITY', 'US', 'USD', TRUE),
    ('BBY', 'Best Buy', 'EQUITY', 'US', 'USD', TRUE),
    ('TECH', 'Bio-Techne', 'EQUITY', 'US', 'USD', TRUE),
    ('BIIB', 'Biogen', 'EQUITY', 'US', 'USD', TRUE),
    ('BLK', 'BlackRock', 'EQUITY', 'US', 'USD', TRUE),
    ('BX', 'Blackstone Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('XYZ', 'Block, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('BE', 'Bloom Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('BNY', 'BNY Mellon', 'EQUITY', 'US', 'USD', TRUE),
    ('BA', 'Boeing', 'EQUITY', 'US', 'USD', TRUE),
    ('BKNG', 'Booking Holdings', 'EQUITY', 'US', 'USD', TRUE),
    ('BSX', 'Boston Scientific', 'EQUITY', 'US', 'USD', TRUE),
    ('BMY', 'Bristol Myers Squibb', 'EQUITY', 'US', 'USD', TRUE),
    ('AVGO', 'Broadcom', 'EQUITY', 'US', 'USD', TRUE),
    ('BR', 'Broadridge Financial Solutions', 'EQUITY', 'US', 'USD', TRUE),
    ('BRO', 'Brown & Brown', 'EQUITY', 'US', 'USD', TRUE),
    ('BF.B', 'Brown–Forman', 'EQUITY', 'US', 'USD', TRUE),
    ('BG', 'Bunge Global', 'EQUITY', 'US', 'USD', TRUE),
    ('BXP', 'BXP, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('CHRW', 'C.H. Robinson', 'EQUITY', 'US', 'USD', TRUE),
    ('CDNS', 'Cadence Design Systems', 'EQUITY', 'US', 'USD', TRUE),
    ('CPT', 'Camden Property Trust', 'EQUITY', 'US', 'USD', TRUE),
    ('COF', 'Capital One', 'EQUITY', 'US', 'USD', TRUE),
    ('CAH', 'Cardinal Health', 'EQUITY', 'US', 'USD', TRUE),
    ('CCL', 'Carnival Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('CARR', 'Carrier Global', 'EQUITY', 'US', 'USD', TRUE),
    ('CVNA', 'Carvana', 'EQUITY', 'US', 'USD', TRUE),
    ('CASY', 'Casey''s', 'EQUITY', 'US', 'USD', TRUE),
    ('CAT', 'Caterpillar Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('CBOE', 'Cboe Global Markets', 'EQUITY', 'US', 'USD', TRUE),
    ('CBRE', 'CBRE Group', 'EQUITY', 'US', 'USD', TRUE),
    ('CDW', 'CDW Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('COR', 'Cencora', 'EQUITY', 'US', 'USD', TRUE),
    ('CNC', 'Centene Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('CNP', 'CenterPoint Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('CF', 'CF Industries', 'EQUITY', 'US', 'USD', TRUE),
    ('CRL', 'Charles River Laboratories', 'EQUITY', 'US', 'USD', TRUE),
    ('SCHW', 'Charles Schwab Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('CHTR', 'Charter Communications', 'EQUITY', 'US', 'USD', TRUE),
    ('CVX', 'Chevron Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('CMG', 'Chipotle Mexican Grill', 'EQUITY', 'US', 'USD', TRUE),
    ('CB', 'Chubb Limited', 'EQUITY', 'US', 'USD', TRUE),
    ('CHD', 'Church & Dwight', 'EQUITY', 'US', 'USD', TRUE),
    ('CIEN', 'Ciena', 'EQUITY', 'US', 'USD', TRUE),
    ('CI', 'Cigna', 'EQUITY', 'US', 'USD', TRUE),
    ('CINF', 'Cincinnati Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('CTAS', 'Cintas', 'EQUITY', 'US', 'USD', TRUE),
    ('CSCO', 'Cisco', 'EQUITY', 'US', 'USD', TRUE),
    ('C', 'Citigroup', 'EQUITY', 'US', 'USD', TRUE),
    ('CFG', 'Citizens Financial Group', 'EQUITY', 'US', 'USD', TRUE),
    ('CLX', 'Clorox', 'EQUITY', 'US', 'USD', TRUE),
    ('CME', 'CME Group', 'EQUITY', 'US', 'USD', TRUE),
    ('CMS', 'CMS Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('KO', 'Coca-Cola Company (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('CTSH', 'Cognizant', 'EQUITY', 'US', 'USD', TRUE),
    ('COHR', 'Coherent Corp.', 'EQUITY', 'US', 'USD', TRUE),
    ('COIN', 'Coinbase', 'EQUITY', 'US', 'USD', TRUE),
    ('CL', 'Colgate-Palmolive', 'EQUITY', 'US', 'USD', TRUE),
    ('CMCSA', 'Comcast', 'EQUITY', 'US', 'USD', TRUE),
    ('FIX', 'Comfort Systems USA', 'EQUITY', 'US', 'USD', TRUE),
    ('COP', 'ConocoPhillips', 'EQUITY', 'US', 'USD', TRUE),
    ('ED', 'Consolidated Edison', 'EQUITY', 'US', 'USD', TRUE),
    ('STZ', 'Constellation Brands', 'EQUITY', 'US', 'USD', TRUE),
    ('CEG', 'Constellation Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('COO', 'Cooper Companies (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('CPRT', 'Copart', 'EQUITY', 'US', 'USD', TRUE),
    ('GLW', 'Corning Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('CPAY', 'Corpay', 'EQUITY', 'US', 'USD', TRUE),
    ('CTVA', 'Corteva', 'EQUITY', 'US', 'USD', TRUE),
    ('CSGP', 'CoStar Group', 'EQUITY', 'US', 'USD', TRUE),
    ('COST', 'Costco', 'EQUITY', 'US', 'USD', TRUE),
    ('CRH', 'CRH plc', 'EQUITY', 'US', 'USD', TRUE),
    ('CRWD', 'CrowdStrike', 'EQUITY', 'US', 'USD', TRUE),
    ('CCI', 'Crown Castle', 'EQUITY', 'US', 'USD', TRUE),
    ('CSX', 'CSX Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('CMI', 'Cummins', 'EQUITY', 'US', 'USD', TRUE),
    ('CVS', 'CVS Health', 'EQUITY', 'US', 'USD', TRUE),
    ('DHR', 'Danaher Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('DRI', 'Darden Restaurants', 'EQUITY', 'US', 'USD', TRUE),
    ('DDOG', 'Datadog', 'EQUITY', 'US', 'USD', TRUE),
    ('DVA', 'DaVita', 'EQUITY', 'US', 'USD', TRUE),
    ('DECK', 'Deckers Brands', 'EQUITY', 'US', 'USD', TRUE),
    ('DE', 'Deere & Company', 'EQUITY', 'US', 'USD', TRUE),
    ('DELL', 'Dell Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('DAL', 'Delta Air Lines', 'EQUITY', 'US', 'USD', TRUE),
    ('DVN', 'Devon Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('DXCM', 'Dexcom', 'EQUITY', 'US', 'USD', TRUE),
    ('FANG', 'Diamondback Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('DLR', 'Digital Realty', 'EQUITY', 'US', 'USD', TRUE),
    ('DG', 'Dollar General', 'EQUITY', 'US', 'USD', TRUE),
    ('DLTR', 'Dollar Tree', 'EQUITY', 'US', 'USD', TRUE),
    ('D', 'Dominion Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('DPZ', 'Domino''s', 'EQUITY', 'US', 'USD', TRUE),
    ('DASH', 'DoorDash', 'EQUITY', 'US', 'USD', TRUE),
    ('DOV', 'Dover Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('DOW', 'Dow Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('DHI', 'D. R. Horton', 'EQUITY', 'US', 'USD', TRUE),
    ('DTE', 'DTE Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('DUK', 'Duke Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('DD', 'DuPont', 'EQUITY', 'US', 'USD', TRUE),
    ('ETN', 'Eaton Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('EBAY', 'eBay Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('ECHO', 'EchoStar', 'EQUITY', 'US', 'USD', TRUE),
    ('ECL', 'Ecolab', 'EQUITY', 'US', 'USD', TRUE),
    ('EIX', 'Edison International', 'EQUITY', 'US', 'USD', TRUE),
    ('EW', 'Edwards Lifesciences', 'EQUITY', 'US', 'USD', TRUE),
    ('ELV', 'Elevance Health', 'EQUITY', 'US', 'USD', TRUE),
    ('EME', 'Emcor', 'EQUITY', 'US', 'USD', TRUE),
    ('EMR', 'Emerson Electric', 'EQUITY', 'US', 'USD', TRUE),
    ('ETR', 'Entergy', 'EQUITY', 'US', 'USD', TRUE),
    ('EOG', 'EOG Resources', 'EQUITY', 'US', 'USD', TRUE),
    ('EQT', 'EQT Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('EFX', 'Equifax', 'EQUITY', 'US', 'USD', TRUE),
    ('EQIX', 'Equinix', 'EQUITY', 'US', 'USD', TRUE),
    ('ERIE', 'Erie Indemnity', 'EQUITY', 'US', 'USD', TRUE),
    ('ESS', 'Essex Property Trust', 'EQUITY', 'US', 'USD', TRUE),
    ('EL', 'Estée Lauder Companies (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('EG', 'Everest Group', 'EQUITY', 'US', 'USD', TRUE),
    ('EVRG', 'Evergy', 'EQUITY', 'US', 'USD', TRUE),
    ('P', 'Everpure', 'EQUITY', 'US', 'USD', TRUE),
    ('ES', 'Eversource Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('EXC', 'Exelon', 'EQUITY', 'US', 'USD', TRUE),
    ('EXE', 'Expand Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('EXPE', 'Expedia Group', 'EQUITY', 'US', 'USD', TRUE),
    ('EXPD', 'Expeditors International', 'EQUITY', 'US', 'USD', TRUE),
    ('EXR', 'Extra Space Storage', 'EQUITY', 'US', 'USD', TRUE),
    ('XOM', 'ExxonMobil', 'EQUITY', 'US', 'USD', TRUE),
    ('FFIV', 'F5, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('FDS', 'FactSet', 'EQUITY', 'US', 'USD', TRUE),
    ('FICO', 'Fair Isaac', 'EQUITY', 'US', 'USD', TRUE),
    ('FAST', 'Fastenal', 'EQUITY', 'US', 'USD', TRUE),
    ('FRT', 'Federal Realty Investment Trust', 'EQUITY', 'US', 'USD', TRUE),
    ('FDX', 'FedEx', 'EQUITY', 'US', 'USD', TRUE),
    ('FDXF', 'FedEx Freight', 'EQUITY', 'US', 'USD', TRUE),
    ('FERG', 'Ferguson Enterprises', 'EQUITY', 'US', 'USD', TRUE),
    ('FIS', 'Fidelity National Information Services', 'EQUITY', 'US', 'USD', TRUE),
    ('FITB', 'Fifth Third Bancorp', 'EQUITY', 'US', 'USD', TRUE),
    ('FSLR', 'First Solar', 'EQUITY', 'US', 'USD', TRUE),
    ('FE', 'FirstEnergy', 'EQUITY', 'US', 'USD', TRUE),
    ('FISV', 'Fiserv', 'EQUITY', 'US', 'USD', TRUE),
    ('FLEX', 'Flex Ltd.', 'EQUITY', 'US', 'USD', TRUE),
    ('F', 'Ford Motor Company', 'EQUITY', 'US', 'USD', TRUE),
    ('FTNT', 'Fortinet', 'EQUITY', 'US', 'USD', TRUE),
    ('FTV', 'Fortive', 'EQUITY', 'US', 'USD', TRUE),
    ('FOXA', 'Fox Corporation (Class A)', 'EQUITY', 'US', 'USD', TRUE),
    ('FOX', 'Fox Corporation (Class B)', 'EQUITY', 'US', 'USD', TRUE),
    ('BEN', 'Franklin Resources', 'EQUITY', 'US', 'USD', TRUE),
    ('FCX', 'Freeport-McMoRan', 'EQUITY', 'US', 'USD', TRUE),
    ('GRMN', 'Garmin', 'EQUITY', 'US', 'USD', TRUE),
    ('IT', 'Gartner', 'EQUITY', 'US', 'USD', TRUE),
    ('GE', 'GE Aerospace', 'EQUITY', 'US', 'USD', TRUE),
    ('GEHC', 'GE HealthCare', 'EQUITY', 'US', 'USD', TRUE),
    ('GEV', 'GE Vernova', 'EQUITY', 'US', 'USD', TRUE),
    ('GEN', 'Gen Digital', 'EQUITY', 'US', 'USD', TRUE),
    ('GNRC', 'Generac', 'EQUITY', 'US', 'USD', TRUE),
    ('GD', 'General Dynamics', 'EQUITY', 'US', 'USD', TRUE),
    ('GIS', 'General Mills', 'EQUITY', 'US', 'USD', TRUE),
    ('GM', 'General Motors', 'EQUITY', 'US', 'USD', TRUE),
    ('GPC', 'Genuine Parts Company', 'EQUITY', 'US', 'USD', TRUE),
    ('GILD', 'Gilead Sciences', 'EQUITY', 'US', 'USD', TRUE),
    ('GPN', 'Global Payments', 'EQUITY', 'US', 'USD', TRUE),
    ('GL', 'Globe Life', 'EQUITY', 'US', 'USD', TRUE),
    ('GDDY', 'GoDaddy', 'EQUITY', 'US', 'USD', TRUE),
    ('GS', 'Goldman Sachs', 'EQUITY', 'US', 'USD', TRUE),
    ('HAL', 'Halliburton', 'EQUITY', 'US', 'USD', TRUE),
    ('HIG', 'Hartford (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('HAS', 'Hasbro', 'EQUITY', 'US', 'USD', TRUE),
    ('HCA', 'HCA Healthcare', 'EQUITY', 'US', 'USD', TRUE),
    ('DOC', 'Healthpeak Properties', 'EQUITY', 'US', 'USD', TRUE),
    ('HSIC', 'Henry Schein', 'EQUITY', 'US', 'USD', TRUE),
    ('HSY', 'Hershey Company (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('HPE', 'Hewlett Packard Enterprise', 'EQUITY', 'US', 'USD', TRUE),
    ('HLT', 'Hilton Worldwide', 'EQUITY', 'US', 'USD', TRUE),
    ('HD', 'Home Depot (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('HONA', 'Honeywell Aerospace', 'EQUITY', 'US', 'USD', TRUE),
    ('HON', 'Honeywell Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('HRL', 'Hormel Foods', 'EQUITY', 'US', 'USD', TRUE),
    ('HST', 'Host Hotels & Resorts', 'EQUITY', 'US', 'USD', TRUE),
    ('HWM', 'Howmet Aerospace', 'EQUITY', 'US', 'USD', TRUE),
    ('HPQ', 'HP Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('HUBB', 'Hubbell Incorporated', 'EQUITY', 'US', 'USD', TRUE),
    ('HUM', 'Humana', 'EQUITY', 'US', 'USD', TRUE),
    ('HBAN', 'Huntington Bancshares', 'EQUITY', 'US', 'USD', TRUE),
    ('HII', 'Huntington Ingalls Industries', 'EQUITY', 'US', 'USD', TRUE),
    ('IBM', 'IBM', 'EQUITY', 'US', 'USD', TRUE),
    ('IEX', 'IDEX Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('IDXX', 'Idexx Laboratories', 'EQUITY', 'US', 'USD', TRUE),
    ('ITW', 'Illinois Tool Works', 'EQUITY', 'US', 'USD', TRUE),
    ('ILMN', 'Illumina, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('INCY', 'Incyte', 'EQUITY', 'US', 'USD', TRUE),
    ('IR', 'Ingersoll Rand', 'EQUITY', 'US', 'USD', TRUE),
    ('PODD', 'Insulet Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('INTC', 'Intel', 'EQUITY', 'US', 'USD', TRUE),
    ('IBKR', 'Interactive Brokers', 'EQUITY', 'US', 'USD', TRUE),
    ('ICE', 'Intercontinental Exchange', 'EQUITY', 'US', 'USD', TRUE),
    ('IFF', 'International Flavors & Fragrances', 'EQUITY', 'US', 'USD', TRUE),
    ('IP', 'International Paper', 'EQUITY', 'US', 'USD', TRUE),
    ('INTU', 'Intuit', 'EQUITY', 'US', 'USD', TRUE),
    ('ISRG', 'Intuitive Surgical', 'EQUITY', 'US', 'USD', TRUE),
    ('IVZ', 'Invesco', 'EQUITY', 'US', 'USD', TRUE),
    ('INVH', 'Invitation Homes', 'EQUITY', 'US', 'USD', TRUE),
    ('IQV', 'IQVIA', 'EQUITY', 'US', 'USD', TRUE),
    ('IRM', 'Iron Mountain', 'EQUITY', 'US', 'USD', TRUE),
    ('JBHT', 'J.B. Hunt', 'EQUITY', 'US', 'USD', TRUE),
    ('JBL', 'Jabil', 'EQUITY', 'US', 'USD', TRUE),
    ('JKHY', 'Jack Henry & Associates', 'EQUITY', 'US', 'USD', TRUE),
    ('J', 'Jacobs Solutions', 'EQUITY', 'US', 'USD', TRUE),
    ('JNJ', 'Johnson & Johnson', 'EQUITY', 'US', 'USD', TRUE),
    ('JCI', 'Johnson Controls', 'EQUITY', 'US', 'USD', TRUE),
    ('JPM', 'JPMorgan Chase', 'EQUITY', 'US', 'USD', TRUE),
    ('KVUE', 'Kenvue', 'EQUITY', 'US', 'USD', TRUE),
    ('KDP', 'Keurig Dr Pepper', 'EQUITY', 'US', 'USD', TRUE),
    ('KEY', 'KeyCorp', 'EQUITY', 'US', 'USD', TRUE),
    ('KEYS', 'Keysight Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('KMB', 'Kimberly-Clark', 'EQUITY', 'US', 'USD', TRUE),
    ('KIM', 'Kimco Realty', 'EQUITY', 'US', 'USD', TRUE),
    ('KMI', 'Kinder Morgan', 'EQUITY', 'US', 'USD', TRUE),
    ('KKR', 'KKR & Co.', 'EQUITY', 'US', 'USD', TRUE),
    ('KLAC', 'KLA Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('KHC', 'Kraft Heinz', 'EQUITY', 'US', 'USD', TRUE),
    ('KR', 'Kroger', 'EQUITY', 'US', 'USD', TRUE),
    ('LHX', 'L3Harris', 'EQUITY', 'US', 'USD', TRUE),
    ('LH', 'Labcorp', 'EQUITY', 'US', 'USD', TRUE),
    ('LRCX', 'Lam Research', 'EQUITY', 'US', 'USD', TRUE),
    ('LVS', 'Las Vegas Sands', 'EQUITY', 'US', 'USD', TRUE),
    ('LDOS', 'Leidos', 'EQUITY', 'US', 'USD', TRUE),
    ('LEN', 'Lennar', 'EQUITY', 'US', 'USD', TRUE),
    ('LII', 'Lennox International', 'EQUITY', 'US', 'USD', TRUE),
    ('LLY', 'Lilly (Eli)', 'EQUITY', 'US', 'USD', TRUE),
    ('LIN', 'Linde plc', 'EQUITY', 'US', 'USD', TRUE),
    ('LYV', 'Live Nation Entertainment', 'EQUITY', 'US', 'USD', TRUE),
    ('LMT', 'Lockheed Martin', 'EQUITY', 'US', 'USD', TRUE),
    ('L', 'Loews Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('LOW', 'Lowe''s', 'EQUITY', 'US', 'USD', TRUE),
    ('LULU', 'Lululemon Athletica', 'EQUITY', 'US', 'USD', TRUE),
    ('LITE', 'Lumentum', 'EQUITY', 'US', 'USD', TRUE),
    ('LYB', 'LyondellBasell', 'EQUITY', 'US', 'USD', TRUE),
    ('MTB', 'M&T Bank', 'EQUITY', 'US', 'USD', TRUE),
    ('MPC', 'Marathon Petroleum', 'EQUITY', 'US', 'USD', TRUE),
    ('MAR', 'Marriott International', 'EQUITY', 'US', 'USD', TRUE),
    ('MRSH', 'Marsh McLennan', 'EQUITY', 'US', 'USD', TRUE),
    ('MLM', 'Martin Marietta Materials', 'EQUITY', 'US', 'USD', TRUE),
    ('MRVL', 'Marvell Technology', 'EQUITY', 'US', 'USD', TRUE),
    ('MAS', 'Masco', 'EQUITY', 'US', 'USD', TRUE),
    ('MA', 'Mastercard', 'EQUITY', 'US', 'USD', TRUE),
    ('MKC', 'McCormick & Company', 'EQUITY', 'US', 'USD', TRUE),
    ('MCD', 'McDonald''s', 'EQUITY', 'US', 'USD', TRUE),
    ('MCK', 'McKesson Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('MDT', 'Medtronic', 'EQUITY', 'US', 'USD', TRUE),
    ('MRK', 'Merck & Co.', 'EQUITY', 'US', 'USD', TRUE),
    ('META', 'Meta Platforms', 'EQUITY', 'US', 'USD', TRUE),
    ('MET', 'MetLife', 'EQUITY', 'US', 'USD', TRUE),
    ('MTD', 'Mettler Toledo', 'EQUITY', 'US', 'USD', TRUE),
    ('MGM', 'MGM Resorts', 'EQUITY', 'US', 'USD', TRUE),
    ('MCHP', 'Microchip Technology', 'EQUITY', 'US', 'USD', TRUE),
    ('MU', 'Micron Technology', 'EQUITY', 'US', 'USD', TRUE),
    ('MSFT', 'Microsoft', 'EQUITY', 'US', 'USD', TRUE),
    ('MAA', 'Mid-America Apartment Communities', 'EQUITY', 'US', 'USD', TRUE),
    ('MRNA', 'Moderna', 'EQUITY', 'US', 'USD', TRUE),
    ('MDLZ', 'Mondelez International', 'EQUITY', 'US', 'USD', TRUE),
    ('MPWR', 'Monolithic Power Systems', 'EQUITY', 'US', 'USD', TRUE),
    ('MNST', 'Monster Beverage', 'EQUITY', 'US', 'USD', TRUE),
    ('MCO', 'Moody''s Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('MS', 'Morgan Stanley', 'EQUITY', 'US', 'USD', TRUE),
    ('MOS', 'Mosaic Company (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('MSI', 'Motorola Solutions', 'EQUITY', 'US', 'USD', TRUE),
    ('MSCI', 'MSCI', 'EQUITY', 'US', 'USD', TRUE),
    ('NDAQ', 'Nasdaq, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('NTAP', 'NetApp', 'EQUITY', 'US', 'USD', TRUE),
    ('NFLX', 'Netflix', 'EQUITY', 'US', 'USD', TRUE),
    ('NEM', 'Newmont', 'EQUITY', 'US', 'USD', TRUE),
    ('NWSA', 'News Corp (Class A)', 'EQUITY', 'US', 'USD', TRUE),
    ('NWS', 'News Corp (Class B)', 'EQUITY', 'US', 'USD', TRUE),
    ('NEE', 'NextEra Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('NKE', 'Nike, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('NI', 'NiSource', 'EQUITY', 'US', 'USD', TRUE),
    ('NDSN', 'Nordson Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('NSC', 'Norfolk Southern', 'EQUITY', 'US', 'USD', TRUE),
    ('NTRS', 'Northern Trust', 'EQUITY', 'US', 'USD', TRUE),
    ('NOC', 'Northrop Grumman', 'EQUITY', 'US', 'USD', TRUE),
    ('NCLH', 'Norwegian Cruise Line Holdings', 'EQUITY', 'US', 'USD', TRUE),
    ('NRG', 'NRG Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('NUE', 'Nucor', 'EQUITY', 'US', 'USD', TRUE),
    ('NVDA', 'Nvidia', 'EQUITY', 'US', 'USD', TRUE),
    ('NVR', 'NVR, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('NXPI', 'NXP Semiconductors', 'EQUITY', 'US', 'USD', TRUE),
    ('ORLY', 'O''Reilly Automotive', 'EQUITY', 'US', 'USD', TRUE),
    ('OXY', 'Occidental Petroleum', 'EQUITY', 'US', 'USD', TRUE),
    ('ODFL', 'Old Dominion', 'EQUITY', 'US', 'USD', TRUE),
    ('OMC', 'Omnicom Group', 'EQUITY', 'US', 'USD', TRUE),
    ('ON', 'ON Semiconductor', 'EQUITY', 'US', 'USD', TRUE),
    ('OKE', 'Oneok', 'EQUITY', 'US', 'USD', TRUE),
    ('ORCL', 'Oracle Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('OTIS', 'Otis Worldwide', 'EQUITY', 'US', 'USD', TRUE),
    ('PCAR', 'Paccar', 'EQUITY', 'US', 'USD', TRUE),
    ('PKG', 'Packaging Corporation of America', 'EQUITY', 'US', 'USD', TRUE),
    ('PLTR', 'Palantir Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('PANW', 'Palo Alto Networks', 'EQUITY', 'US', 'USD', TRUE),
    ('PSKY', 'Paramount Skydance Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('PH', 'Parker Hannifin', 'EQUITY', 'US', 'USD', TRUE),
    ('PAYX', 'Paychex', 'EQUITY', 'US', 'USD', TRUE),
    ('PYPL', 'PayPal', 'EQUITY', 'US', 'USD', TRUE),
    ('PNR', 'Pentair', 'EQUITY', 'US', 'USD', TRUE),
    ('PEP', 'PepsiCo', 'EQUITY', 'US', 'USD', TRUE),
    ('PFE', 'Pfizer', 'EQUITY', 'US', 'USD', TRUE),
    ('PCG', 'PG&E Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('PM', 'Philip Morris International', 'EQUITY', 'US', 'USD', TRUE),
    ('PSX', 'Phillips 66', 'EQUITY', 'US', 'USD', TRUE),
    ('PNW', 'Pinnacle West Capital', 'EQUITY', 'US', 'USD', TRUE),
    ('PNC', 'PNC Financial Services', 'EQUITY', 'US', 'USD', TRUE),
    ('PPG', 'PPG Industries', 'EQUITY', 'US', 'USD', TRUE),
    ('PPL', 'PPL Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('PFG', 'Principal Financial Group', 'EQUITY', 'US', 'USD', TRUE),
    ('PG', 'Procter & Gamble', 'EQUITY', 'US', 'USD', TRUE),
    ('PGR', 'Progressive Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('PLD', 'Prologis', 'EQUITY', 'US', 'USD', TRUE),
    ('PRU', 'Prudential Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('PEG', 'Public Service Enterprise Group', 'EQUITY', 'US', 'USD', TRUE),
    ('PTC', 'PTC Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('PSA', 'Public Storage', 'EQUITY', 'US', 'USD', TRUE),
    ('PHM', 'PulteGroup', 'EQUITY', 'US', 'USD', TRUE),
    ('PWR', 'Quanta Services', 'EQUITY', 'US', 'USD', TRUE),
    ('QCOM', 'Qualcomm', 'EQUITY', 'US', 'USD', TRUE),
    ('DGX', 'Quest Diagnostics', 'EQUITY', 'US', 'USD', TRUE),
    ('Q', 'Qnity Electronics', 'EQUITY', 'US', 'USD', TRUE),
    ('RL', 'Ralph Lauren Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('RJF', 'Raymond James Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('RDDT', 'Reddit', 'EQUITY', 'US', 'USD', TRUE),
    ('RTX', 'RTX Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('O', 'Realty Income', 'EQUITY', 'US', 'USD', TRUE),
    ('REG', 'Regency Centers', 'EQUITY', 'US', 'USD', TRUE),
    ('REGN', 'Regeneron Pharmaceuticals', 'EQUITY', 'US', 'USD', TRUE),
    ('RF', 'Regions Financial Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('RSG', 'Republic Services', 'EQUITY', 'US', 'USD', TRUE),
    ('RMD', 'ResMed|', 'EQUITY', 'US', 'USD', TRUE),
    ('RVTY', 'Revvity', 'EQUITY', 'US', 'USD', TRUE),
    ('HOOD', 'Robinhood Markets', 'EQUITY', 'US', 'USD', TRUE),
    ('ROK', 'Rockwell Automation', 'EQUITY', 'US', 'USD', TRUE),
    ('ROL', 'Rollins, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('ROP', 'Roper Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('ROST', 'Ross Stores', 'EQUITY', 'US', 'USD', TRUE),
    ('RCL', 'Royal Caribbean Group', 'EQUITY', 'US', 'USD', TRUE),
    ('SPGI', 'S&P Global', 'EQUITY', 'US', 'USD', TRUE),
    ('CRM', 'Salesforce', 'EQUITY', 'US', 'USD', TRUE),
    ('SNDK', 'Sandisk', 'EQUITY', 'US', 'USD', TRUE),
    ('SBAC', 'SBA Communications', 'EQUITY', 'US', 'USD', TRUE),
    ('SLB', 'Schlumberger', 'EQUITY', 'US', 'USD', TRUE),
    ('STX', 'Seagate Technology', 'EQUITY', 'US', 'USD', TRUE),
    ('SRE', 'Sempra', 'EQUITY', 'US', 'USD', TRUE),
    ('NOW', 'ServiceNow', 'EQUITY', 'US', 'USD', TRUE),
    ('SHW', 'Sherwin-Williams', 'EQUITY', 'US', 'USD', TRUE),
    ('SPG', 'Simon Property Group', 'EQUITY', 'US', 'USD', TRUE),
    ('SWKS', 'Skyworks Solutions', 'EQUITY', 'US', 'USD', TRUE),
    ('SJM', 'J.M. Smucker Company (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('SW', 'Smurfit Westrock', 'EQUITY', 'US', 'USD', TRUE),
    ('SNA', 'Snap-on', 'EQUITY', 'US', 'USD', TRUE),
    ('SOLV', 'Solventum', 'EQUITY', 'US', 'USD', TRUE),
    ('SO', 'Southern Company', 'EQUITY', 'US', 'USD', TRUE),
    ('LUV', 'Southwest Airlines', 'EQUITY', 'US', 'USD', TRUE),
    ('SWK', 'Stanley Black & Decker', 'EQUITY', 'US', 'USD', TRUE),
    ('SBUX', 'Starbucks', 'EQUITY', 'US', 'USD', TRUE),
    ('STT', 'State Street Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('STLD', 'Steel Dynamics', 'EQUITY', 'US', 'USD', TRUE),
    ('STE', 'Steris', 'EQUITY', 'US', 'USD', TRUE),
    ('SYK', 'Stryker Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('SMCI', 'Supermicro', 'EQUITY', 'US', 'USD', TRUE),
    ('SYF', 'Synchrony Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('SNPS', 'Synopsys', 'EQUITY', 'US', 'USD', TRUE),
    ('SYY', 'Sysco', 'EQUITY', 'US', 'USD', TRUE),
    ('TMUS', 'T-Mobile US', 'EQUITY', 'US', 'USD', TRUE),
    ('TROW', 'T. Rowe Price', 'EQUITY', 'US', 'USD', TRUE),
    ('TTWO', 'Take-Two Interactive', 'EQUITY', 'US', 'USD', TRUE),
    ('TPR', 'Tapestry, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('TRGP', 'Targa Resources', 'EQUITY', 'US', 'USD', TRUE),
    ('TGT', 'Target Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('TEL', 'TE Connectivity', 'EQUITY', 'US', 'USD', TRUE),
    ('TDY', 'Teledyne Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('TER', 'Teradyne', 'EQUITY', 'US', 'USD', TRUE),
    ('TSLA', 'Tesla, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('TXN', 'Texas Instruments', 'EQUITY', 'US', 'USD', TRUE),
    ('TPL', 'Texas Pacific Land Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('TXT', 'Textron', 'EQUITY', 'US', 'USD', TRUE),
    ('TMO', 'Thermo Fisher Scientific', 'EQUITY', 'US', 'USD', TRUE),
    ('TJX', 'TJX Companies', 'EQUITY', 'US', 'USD', TRUE),
    ('TKO', 'TKO Group Holdings', 'EQUITY', 'US', 'USD', TRUE),
    ('TSCO', 'Tractor Supply', 'EQUITY', 'US', 'USD', TRUE),
    ('TT', 'Trane Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('TDG', 'TransDigm Group', 'EQUITY', 'US', 'USD', TRUE),
    ('TRV', 'Travelers Companies (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('TRMB', 'Trimble Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('TFC', 'Truist Financial', 'EQUITY', 'US', 'USD', TRUE),
    ('TYL', 'Tyler Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('TSN', 'Tyson Foods', 'EQUITY', 'US', 'USD', TRUE),
    ('USB', 'U.S. Bancorp', 'EQUITY', 'US', 'USD', TRUE),
    ('UBER', 'Uber', 'EQUITY', 'US', 'USD', TRUE),
    ('UDR', 'UDR, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('ULTA', 'Ulta Beauty', 'EQUITY', 'US', 'USD', TRUE),
    ('UNP', 'Union Pacific Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('UAL', 'United Airlines Holdings', 'EQUITY', 'US', 'USD', TRUE),
    ('UPS', 'United Parcel Service', 'EQUITY', 'US', 'USD', TRUE),
    ('URI', 'United Rentals', 'EQUITY', 'US', 'USD', TRUE),
    ('UNH', 'UnitedHealth Group', 'EQUITY', 'US', 'USD', TRUE),
    ('UHS', 'Universal Health Services', 'EQUITY', 'US', 'USD', TRUE),
    ('VLO', 'Valero Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('VEEV', 'Veeva Systems', 'EQUITY', 'US', 'USD', TRUE),
    ('VTR', 'Ventas', 'EQUITY', 'US', 'USD', TRUE),
    ('VLTO', 'Veralto', 'EQUITY', 'US', 'USD', TRUE),
    ('VRSN', 'Verisign', 'EQUITY', 'US', 'USD', TRUE),
    ('VRSK', 'Verisk Analytics', 'EQUITY', 'US', 'USD', TRUE),
    ('VZ', 'Verizon', 'EQUITY', 'US', 'USD', TRUE),
    ('VRTX', 'Vertex Pharmaceuticals', 'EQUITY', 'US', 'USD', TRUE),
    ('VRT', 'Vertiv', 'EQUITY', 'US', 'USD', TRUE),
    ('VTRS', 'Viatris', 'EQUITY', 'US', 'USD', TRUE),
    ('VICI', 'Vici Properties', 'EQUITY', 'US', 'USD', TRUE),
    ('V', 'Visa Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('VST', 'Vistra Corp.', 'EQUITY', 'US', 'USD', TRUE),
    ('VMRK', 'Vivmark Residential', 'EQUITY', 'US', 'USD', TRUE),
    ('VMC', 'Vulcan Materials Company', 'EQUITY', 'US', 'USD', TRUE),
    ('WRB', 'W. R. Berkley Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('GWW', 'W. W. Grainger', 'EQUITY', 'US', 'USD', TRUE),
    ('WAB', 'Wabtec', 'EQUITY', 'US', 'USD', TRUE),
    ('WMT', 'Walmart', 'EQUITY', 'US', 'USD', TRUE),
    ('DIS', 'Walt Disney Company (The)', 'EQUITY', 'US', 'USD', TRUE),
    ('WBD', 'Warner Bros. Discovery', 'EQUITY', 'US', 'USD', TRUE),
    ('WM', 'Waste Management', 'EQUITY', 'US', 'USD', TRUE),
    ('WAT', 'Waters Corporation', 'EQUITY', 'US', 'USD', TRUE),
    ('WEC', 'WEC Energy Group', 'EQUITY', 'US', 'USD', TRUE),
    ('WFC', 'Wells Fargo', 'EQUITY', 'US', 'USD', TRUE),
    ('WELL', 'Welltower', 'EQUITY', 'US', 'USD', TRUE),
    ('WST', 'West Pharmaceutical Services', 'EQUITY', 'US', 'USD', TRUE),
    ('WDC', 'Western Digital', 'EQUITY', 'US', 'USD', TRUE),
    ('WY', 'Weyerhaeuser', 'EQUITY', 'US', 'USD', TRUE),
    ('WSM', 'Williams-Sonoma, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('WMB', 'Williams Companies', 'EQUITY', 'US', 'USD', TRUE),
    ('WTW', 'Willis Towers Watson', 'EQUITY', 'US', 'USD', TRUE),
    ('WDAY', 'Workday, Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('WYNN', 'Wynn Resorts', 'EQUITY', 'US', 'USD', TRUE),
    ('XEL', 'Xcel Energy', 'EQUITY', 'US', 'USD', TRUE),
    ('XYL', 'Xylem Inc.', 'EQUITY', 'US', 'USD', TRUE),
    ('YUM', 'Yum! Brands', 'EQUITY', 'US', 'USD', TRUE),
    ('ZBRA', 'Zebra Technologies', 'EQUITY', 'US', 'USD', TRUE),
    ('ZBH', 'Zimmer Biomet', 'EQUITY', 'US', 'USD', TRUE),
    ('ZTS', 'Zoetis', 'EQUITY', 'US', 'USD', TRUE)
ON CONFLICT (symbol, market) DO UPDATE SET
    instrument_name = EXCLUDED.instrument_name,
    is_tradable = EXCLUDED.is_tradable;
